export const ENV = {
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  higgsfieldApiKeyId: process.env.HIGGSFIELD_API_KEY_ID ?? "",
  higgsfieldApiKeySecret: process.env.HIGGSFIELD_API_KEY_SECRET ?? "",
  clipdropApiKey: process.env.CLIPDROP_API_KEY ?? "",
  publicSiteUrl: (process.env.PUBLIC_SITE_URL ?? "https://fingerprintsau.com").replace(/\/+$/, ""),
  launchBonusEndsAt: process.env.LAUNCH_BONUS_ENDS_AT ?? "",
  launchBonusCredits: Number(process.env.LAUNCH_BONUS_CREDITS ?? 100),
  freeBatchMaxListings: Number(process.env.FREE_BATCH_MAX_LISTINGS ?? 1),
  businessAbn: process.env.BUSINESS_ABN ?? "",
};
